# GENERATED by scripts/ops/wavegen.py from ops/waves/lewm_graft/spec.yaml -- do not edit by hand.

# Run ON an instance. Every check here corresponds to a failure
# that has actually cost work before.
set -uo pipefail
source /root/.dreamer_vast_env
fail=0
ok () { printf "  PASS %s\n" "$1"; }
bad () { printf "  FAIL %s\n" "$1"; fail=1; }

echo "== fork present (an empty $REPO fails as scattered ENOENT, never one message) =="
for f in scripts/env.sh scripts/ops/instance_helpers.sh probing/__init__.py; do
  [ -e "$REPO/$f" ] && ok "$f" || bad "MISSING $REPO/$f -- run push-repo"
done

echo "== interpreter =="
"${CONDA_ENV:-/venv/main}/bin/python" -c "import sys" 2>/dev/null \
  && ok "python in $CONDA_ENV" || bad "python broken in ${CONDA_ENV:-/venv/main}"

echo "== transfer tooling =="
for b in rsync tar; do
  p="$(command -v "$b" 2>/dev/null)"
  if [ -z "$p" ]; then bad "MISSING $b"
  elif [ ! -x "$p" ]; then bad "$b not executable ($p)"
  elif [ ! -s "$p" ]; then bad "$b is a 0-byte stub ($p) -- reinstall it"
  else ok "$b $(du -h "$p" | cut -f1)"; fi
done

echo "== disk =="
pct="$(df -P "$RUNROOT" | awk 'NR==2{gsub(/%/,"",$5); print $5}')"
[ "${pct:-100}" -lt 90 ] && ok "disk ${pct}% used" || bad "disk ${pct}% used"

echo "== donors =="
[ -e "$RUNROOT/axis1_finger/pxq1m/manifest.json" ] && ok axis1_finger/pxq1m/manifest.json || bad "MISSING donor axis1_finger/pxq1m/manifest.json"
[ -e "$RUNROOT/axis1_finger/pxq1m/side0" ] && ok axis1_finger/pxq1m/side0 || bad "MISSING donor axis1_finger/pxq1m/side0"
[ -e "$RUNROOT/axis1_finger/pxq1m/side1" ] && ok axis1_finger/pxq1m/side1 || bad "MISSING donor axis1_finger/pxq1m/side1"
[ -e "$RUNROOT/lewm_distill_finger_s0_seed4/ckpt" ] && ok lewm_distill_finger_s0_seed4/ckpt || bad "MISSING donor lewm_distill_finger_s0_seed4/ckpt"
[ -e "$RUNROOT/lewm_distill_finger_s0_seed5/ckpt" ] && ok lewm_distill_finger_s0_seed5/ckpt || bad "MISSING donor lewm_distill_finger_s0_seed5/ckpt"
[ -e "$RUNROOT/lewm_distill_finger_s0_seed6/ckpt" ] && ok lewm_distill_finger_s0_seed6/ckpt || bad "MISSING donor lewm_distill_finger_s0_seed6/ckpt"
[ -e "$RUNROOT/lewm_distill_finger_s0_seed8/ckpt" ] && ok lewm_distill_finger_s0_seed8/ckpt || bad "MISSING donor lewm_distill_finger_s0_seed8/ckpt"
[ -e "$RUNROOT/lewm_distill_finger_s1_seed4/ckpt" ] && ok lewm_distill_finger_s1_seed4/ckpt || bad "MISSING donor lewm_distill_finger_s1_seed4/ckpt"
[ -e "$RUNROOT/lewm_distill_finger_s1_seed5/ckpt" ] && ok lewm_distill_finger_s1_seed5/ckpt || bad "MISSING donor lewm_distill_finger_s1_seed5/ckpt"
[ -e "$RUNROOT/lewm_distill_finger_s1_seed8/ckpt" ] && ok lewm_distill_finger_s1_seed8/ckpt || bad "MISSING donor lewm_distill_finger_s1_seed8/ckpt"

echo "== helpers =="
type dv3_queue_or_add >/dev/null 2>&1 && ok "helpers loaded ($(dv3_version))" \
  || bad "helpers not loaded -- run push-repo"

[ "$fail" -eq 0 ] && echo "PREFLIGHT PASS" || echo "PREFLIGHT FAIL"
exit "$fail"
