# GENERATED by scripts/ops/wavegen.py from ops/waves/reacher_domain/spec.yaml -- do not edit by hand.

# Ship the wave dir to an instance, then queue each lane.
#   usage: submit.sh <instance>
set -euo pipefail
N="${1:?usage: submit.sh <instance>}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DV3OPS_ROOT="${DV3OPS_ROOT:-/home/rickybao/projects/dreamerv3}"
[ -f "$DV3OPS_ROOT/scripts/ops/lib/common.sh" ] || {
  echo "ERROR: repo not found at DV3OPS_ROOT=$DV3OPS_ROOT" >&2
  echo "       (set DV3OPS_ROOT if the repo lives elsewhere on this machine)" >&2
  exit 2; }

source "$DV3OPS_ROOT/scripts/ops/lib/common.sh"
dv3_require_instance "$N"
REMOTE_ROOT="$(dv3_ssh_dv3 "$N" 'printf %s "$RUNROOT"')"
[ -n "$REMOTE_ROOT" ] || { echo "ERROR: cannot read RUNROOT on instance $N" >&2; exit 1; }
REMOTE="$REMOTE_ROOT/_waves/reacher_domain"

# rsync rather than heredoc: no quoting survives ssh reliably,
# and it leaves the exact submitted commands on the instance.
dv3_ssh_dv3 "$N" "mkdir -p \"$REMOTE\""
# --checksum: these are small text files that can be
# regenerated at the same size, and size+mtime would skip them.
rsync -az --checksum --info=progress2 \
  -e "ssh -p $(dv3_port "$N") ${DV3_SSH_OPTS[*]}" \
  "$HERE/" "root@$(dv3_ip "$N"):$REMOTE/"

echo "-- stage fit_adapt_task lane 0: 3 task(s) --"
dv3_ssh_dv3 "$N" "DV3_ABORT_ON_FAIL=1 dv3_queue_or_add \"$REMOTE/lane_fit_adapt_task_0.cmds\" 0"
echo "-- stage fit_adapt_task lane 1: 3 task(s) --"
dv3_ssh_dv3 "$N" "DV3_ABORT_ON_FAIL=1 dv3_queue_or_add \"$REMOTE/lane_fit_adapt_task_1.cmds\" 1"
echo "-- stage fit_adapt_apt lane 0: 3 task(s) --"
dv3_ssh_dv3 "$N" "DV3_ABORT_ON_FAIL=1 dv3_queue_or_add \"$REMOTE/lane_fit_adapt_apt_0.cmds\" 0"
echo "-- stage fit_adapt_apt lane 1: 3 task(s) --"
dv3_ssh_dv3 "$N" "DV3_ABORT_ON_FAIL=1 dv3_queue_or_add \"$REMOTE/lane_fit_adapt_apt_1.cmds\" 1"

echo "submitted. verify with: dv3ops status $N"
