"""End-to-end Gate D0 pipeline self-check on synthetic beliefs.

Run: python -m d0.selfcheck [--out artifacts/d0_selfcheck/report.md]

Validates, before any E2 run exists, that the frozen analysis pipeline
(1) detects the pre-registered P1 signature exactly when a dissociation is
constructed, (2) stays silent on a null where the dose grid changes
nothing, (3) preserves the estimator facts from the synthetic check
(bracket in expectation, plug-in mean rising at the half rollout count),
and (4) produces the full decision-memo report tables.
"""

import argparse
import os

import numpy as np

from . import analysis
from . import synthetic


def run_task(name, null, seed):
  cells = synthetic.make_task(null=null, seed=seed)
  e1_sig, e1_eps = cells['E1']
  thresholds = analysis.quadrant_thresholds(e1_sig)
  e1 = analysis.analyze_cell(e1_sig, thresholds, e1_eps, dose='E1',
                             seed=seed)
  doses = []
  for dose_name in ('d8x1', 'd32x1', 'd32x3'):
    sig, eps = cells[dose_name]
    doses.append(analysis.analyze_cell(sig, thresholds, eps,
                                       dose=dose_name, seed=seed))
  p1 = analysis.evaluate_p1(e1, doses)
  report = analysis.render_report(name, e1, doses, p1)
  return e1, doses, p1, report


def main(argv=None):
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument('--out', default='artifacts/d0_selfcheck/report.md')
  parser.add_argument('--seed', type=int, default=20260703)
  args = parser.parse_args(argv)

  blocks = ['# Gate D0 pipeline self-check (synthetic beliefs)', '',
            'Generated by `python -m d0.selfcheck`. Positive tasks must '
            'PASS P1; the null task must FAIL it. See d0/synthetic.py for '
            'the generative model.', '']
  failures = []

  for i, task in enumerate(('synthetic_pos_a', 'synthetic_pos_b')):
    e1, doses, (ok, _), report = run_task(task, null=False,
                                          seed=args.seed + 10 * i)
    blocks.append(report)
    if not ok:
      failures.append(f'{task}: P1 did not trigger on a constructed positive')
    # Estimator facts must survive the pipeline plumbing:
    for cell in [e1] + doses:
      if not cell.bracket_width_full > 0:
        failures.append(f'{task}/{cell.dose}: bracket width not positive')
      if not cell.plugin_shift_half > 0:
        failures.append(f'{task}/{cell.dose}: plug-in mean did not rise '
                        'at the half rollout count')

  e1, doses, (ok, checks), report = run_task('synthetic_null', null=True,
                                             seed=args.seed + 99)
  blocks.append(report)
  if ok:
    failures.append('synthetic_null: P1 triggered on a null')

  verdict = 'ALL CHECKS PASSED' if not failures else 'FAILURES:\n- ' + \
      '\n- '.join(failures)
  blocks.append(f'## Verdict\n\n{verdict}\n')

  os.makedirs(os.path.dirname(args.out) or '.', exist_ok=True)
  with open(args.out, 'w') as f:
    f.write('\n'.join(blocks))
  print('\n'.join(blocks))
  if failures:
    raise SystemExit(1)


if __name__ == '__main__':
  main()
