#!/usr/bin/env python3
"""Generate every per-wave artifact from one spec.  (dv3ops P1, 2026-08-14)

Emits into ops/waves/<wave_id>/generated/:

  RUN_IDS.txt          the approval gate -- expanded ids and counts
  runs.json            canonical run table (consumed by check/pull/bundle)
  lane_<stage>_<n>.cmds  queue command files, pairs already grouped
  submit.sh            rsync the wave dir to an instance, then queue each lane
  preflight_remote.sh  assertions to run ON an instance before submitting
  push_donors.sh       donor rsync, include-list derived from spec inputs
  pull_results.sh      two-pass result pull (payload + mutable-state refresh)
  bundle.sh            bundle + COMPLETION.txt + manifest

The point is not convenience. These four things -- what gets submitted, what
counts as done, what gets pulled, what goes in the bundle -- were previously
written by hand as four independent expressions of the same run set, with
nothing forcing them to agree.

Usage:
  wavegen.py <wave_dir_or_spec> [--lanes 0,1,2,3] [--out DIR]
"""
from __future__ import annotations

import argparse
import json
import os
import shlex
import stat
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wavespec  # noqa: E402
from wavespec import SpecError  # noqa: E402

HEADER = "# GENERATED by scripts/ops/wavegen.py from {spec} -- do not edit by hand.\n"

# Generated scripts must locate the repo without counting "../" levels: the
# depth changes with --out, and an off-by-one silently sources nothing.
ROOT_PREAMBLE = """DV3OPS_ROOT="${{DV3OPS_ROOT:-{root}}}"
[ -f "$DV3OPS_ROOT/scripts/ops/lib/common.sh" ] || {{
  echo "ERROR: repo not found at DV3OPS_ROOT=$DV3OPS_ROOT" >&2
  echo "       (set DV3OPS_ROOT if the repo lives elsewhere on this machine)" >&2
  exit 2; }}
"""


def _repo_root() -> Path:
  return Path(__file__).resolve().parent.parent.parent


def _w(path: Path, text: str, executable: bool = False) -> None:
  path.write_text(text)
  if executable:
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)


# --------------------------------------------------------------------------
# command files
# --------------------------------------------------------------------------

def _logged(cmd: str, run_id: str) -> str:
  """Wrap one command so its own per-run log gets START/DONE and an rc.

  `set +e` inside the subshell is deliberate: without it the failing command
  exits before `rc=$?`, so a failed run logs a START and nothing else.
  """
  return (f'( set +e; echo "===== [$(date)] START {run_id} ====="; {cmd}; rc=$?; '
          f'echo "===== [$(date)] DONE rc=$rc {run_id} ====="; exit $rc ) '
          f'>> "$RUNROOT/_cloud_logs/{run_id}.out" 2>&1')


def cmd_line(unit: list[wavespec.Run], label: str) -> str:
  """One queue line per co-resident unit.

  A pair is ONE queued task: both members start together and the lane does not
  advance until both exit, failing if either does. That barrier is what stands
  in for a VRAM-compatibility model -- the lane can never place an unknown
  neighbour next to a running task.

  Single runs and pairs take the SAME shape on purpose. They used to differ --
  a lone run was emitted as `DV3_TASK_NAME=x ( ... ) >> log`, which is a bash
  syntax error: an assignment prefix may precede a simple command, never a
  compound one like a subshell. Bash rejected the line before running anything,
  so all 16 ridge tasks on instance 7 died with rc=2 in 0s (2026-08-15). Only
  per_gpu=1 stages were affected, which is why the paired tm2 wave never showed
  it. Keeping one code path means a fix here cannot miss the other case.

  The `DV3_TASK_NAME=` prefix stays textually first: the supervisor scrapes the
  task name out of the line with a regex before executing it.
  """
  parts = ['set -uo pipefail', 'source /root/.dreamer_vast_env',
           'cd "$REPO"', 'mkdir -p "$RUNROOT/_cloud_logs"']
  # Create the parent of any output that is a FILE in a shared folder.
  # A stage writing per-run directories needs nothing: its driver creates the
  # dir. But a probe stage writes $RUNROOT/<folder>/<run>.json, and nothing
  # creates <folder> -- so the probe does its whole GPU pass and then dies on
  # the open() at the very end. That cost a full run on instances 2 and 3
  # (2026-08-15); instance 7 survived only because the folder happened to
  # exist there from the smoke test.
  #
  # Parents only, never the run dir itself: pre-creating an empty run dir can
  # make a driver believe it is resuming.
  outdirs = sorted({os.path.dirname(o) for r in unit for o in r.outputs}
                   - {"", "."})
  parts += [f'mkdir -p "$RUNROOT/{d}"' for d in outdirs]
  if len(unit) == 1:
    r = unit[0]
    parts.append(_logged(r.cmd, r.run_id))
    name = r.run_id
  else:
    waits = []
    for i, r in enumerate(unit, start=1):
      parts.append(f"{_logged(r.cmd, r.run_id)} & p{i}=$!")
      waits.append(i)
    for i in waits:
      parts.append(f"wait $p{i}; r{i}=$?")
    cond = " || ".join(f"[ $r{i} -ne 0 ]" for i in waits)
    parts.append(f"if {cond}; then exit 1; fi")
    name = label
  body = "; ".join(parts)
  return f"DV3_TASK_NAME={name} bash -lc {shlex.quote(body)}"


# --------------------------------------------------------------------------
# rsync include lists
# --------------------------------------------------------------------------

def include_args(paths: list[str]) -> list[str]:
  """rsync --include chain for a set of RUNROOT-relative paths.

  rsync only descends into directories it has been told to include, so every
  parent of a wanted path needs its own --include before the final catch-all
  exclude. Getting this wrong silently transfers nothing, which on a paid
  instance looks exactly like a slow network.
  """
  includes: list[str] = []
  seen: set[str] = set()
  for p in sorted(set(paths)):
    parts = [x for x in p.strip("/").split("/") if x]
    for i in range(1, len(parts)):
      d = "/" + "/".join(parts[:i]) + "/"
      if d not in seen:
        seen.add(d)
        includes.append(f"--include={shlex.quote(d)}")
    # Emit BOTH the bare path and the /*** form. The spec does not say whether
    # a declared input is a file or a directory, and guessing wrong fails
    # silently: `config.yaml/***` matches nothing, so the file is skipped and
    # the transfer looks merely slow rather than incomplete. The bare include
    # covers files, the /*** covers directory contents, and an unused include
    # costs nothing.
    leaf = "/" + "/".join(parts)
    for form in (leaf, leaf + "/***"):
      if form not in seen:
        seen.add(form)
        includes.append(f"--include={shlex.quote(form)}")
  return includes


# --------------------------------------------------------------------------
# generators
# --------------------------------------------------------------------------

def _gen_slurm(spec: wavespec.WaveSpec, runs: list[wavespec.Run], hdr: str) -> str:
  """Cap-aware, re-runnable sbatch submission for rcc-slurm stages.

  Three things this encodes that a hand-written loop keeps having to remember:

  1. RCC caps submitted+running jobs (12 by default). Blowing past it silently
     drops submissions, so the script submits up to the cap and tells you how
     many are left -- rerun until it says none, the same shape as
     submit_all.sh's MAX_JOBS.
  2. `--export=ALL` inherits the submitting shell. Submitting from a shell with
     modules loaded leaks their environment into the job and has produced
     segfaults; this refuses to submit from a dirty shell rather than letting
     you find out an hour later.
  3. Runs already complete (by the spec's own predicates) or already queued
     under the same job name are skipped, so rerunning is safe.
  """
  lines = [hdr.rstrip("\n"),
           ("""# Submit this wave's rcc-slurm stages. Re-runnable: run until it reports 0 left.
#   usage: submit_rcc.sh [--dry-run]
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
{root_preamble}cd "$DV3OPS_ROOT"
source scripts/env.sh

DRY=0; [ "${1:-}" = "--dry-run" ] && DRY=1
MAX_JOBS="${MAX_JOBS:-12}"

# (2) module leakage: --export=ALL carries this shell into every job.
if [ -n "${LOADEDMODULES:-}" ] || [ -n "${_LMFILES_:-}" ]; then
  echo "REFUSING TO SUBMIT: modules are loaded in this shell." >&2
  echo "  LOADEDMODULES=${LOADEDMODULES:-}" >&2
  echo "  --export=ALL would leak them into every job; this has segfaulted before." >&2
  echo "  Open a clean login shell, 'source scripts/env.sh', and rerun." >&2
  exit 2
fi

command -v squeue >/dev/null 2>&1 || {
  echo "ERROR: squeue not found -- run this on an RCC login node." >&2; exit 2; }
cur="$(squeue -h -u "$USER" | wc -l)" || {
  echo "ERROR: squeue failed; refusing to guess the queue depth and risk" >&2
  echo "       submitting past the cap." >&2; exit 2; }
slots=$(( MAX_JOBS - cur ))
echo "slurm: $cur job(s) in queue, cap $MAX_JOBS, $slots slot(s) free"
[ "$slots" -gt 0 ] || { echo "at cap; rerun later"; exit 0; }

queued="$(squeue -h -u "$USER" -o '%j' 2>/dev/null || true)"
submitted=0; skipped=0; left=0
""").replace("{root_preamble}", ROOT_PREAMBLE.format(root=shlex.quote(str(_repo_root()))))]

  for r in runs:
    sb = r.sbatch
    exports = ",".join(f"{k}={shlex.quote(str(v))}" for k, v in (sb.get("export") or {}).items())
    opts = [
        f'--account="$SLURM_ACCOUNT"', f'--partition="$SLURM_PARTITION"',
        f'--gres={shlex.quote(str(sb.get("gres", "$SLURM_GRES")))}'.replace(
            "'$SLURM_GRES'", '"$SLURM_GRES"'),
        f'--time={shlex.quote(str(sb.get("time", "12:00:00")))}',
        f'--job-name={shlex.quote(r.run_id)}',
    ]
    for extra in (sb.get("options") or []):
      opts.append(str(extra))
    base = "ALL,REPO=\"$REPO\",RUNROOT=\"$RUNROOT\",CONDA_ENV=\"$CONDA_ENV\",MANIFEST=\"$MANIFEST\""
    lines.append(f"""
# --- {r.run_id} ---
if printf '%s\\n' "$queued" | grep -qxF {shlex.quote(r.run_id)}; then
  echo "  SKIP already queued: {r.run_id}"; skipped=$((skipped+1))
elif [ "$slots" -le 0 ]; then
  left=$((left+1))
else
  if [ "$DRY" = 1 ]; then
    echo "  WOULD SUBMIT {r.run_id}"
  else
    sbatch {' '.join(opts)} \\
      --export={base},{exports} \\
      "$REPO/{sb['script']}"
  fi
  submitted=$((submitted+1)); slots=$((slots-1))
fi""")

  lines.append("""
echo
echo "submitted=$submitted skipped=$skipped left=$left"
[ "$left" -eq 0 ] && echo "all submitted" \\
  || echo "$left run(s) did not fit under the cap -- rerun this script when jobs drain"
""")
  return "\n".join(lines) + "\n"


def gen(spec: wavespec.WaveSpec, out: Path, lanes: list[str]) -> dict:
  out.mkdir(parents=True, exist_ok=True)
  hdr = HEADER.format(spec=spec.path)
  all_runs = spec.runs()
  summary: dict = {"wave_id": spec.wave_id, "stages": {}, "lane_files": []}

  # -- RUN_IDS.txt : the approval gate --------------------------------------
  lines = [f"wave_id: {spec.wave_id}", f"spec:    {spec.path}"]
  if spec.prereg:
    lines.append(f"prereg:  {spec.prereg}")
  lines.append("")
  for st in spec.stages:
    runs = st.expanded()
    summary["stages"][st.name] = {
        "count": len(runs), "target": st.target, "kind": st.kind,
        "on_failure": st.on_failure,
        "per_gpu": spec.kinds[st.kind].per_gpu if st.kind in spec.kinds else 1,
    }
    lines.append(f"=== stage {st.name}  [{st.target}]  kind={st.kind}  "
                 f"on_failure={st.on_failure}  n={len(runs)} ===")
    lines.extend(f"  {r.run_id}" for r in runs)
    lines.append("")
  lines.append(f"TOTAL RUNS: {len(all_runs)}")
  lines.append("")
  lines.append("Check this list against the prereg before submitting. run_ids are")
  lines.append("consumed by frozen readers and the ledger; a wrong expansion here")
  lines.append("propagates into every downstream artifact.")
  _w(out / "RUN_IDS.txt", "\n".join(lines) + "\n")

  # -- runs.json : the canonical table ---------------------------------------
  _w(out / "runs.json", json.dumps({
      "wave_id": spec.wave_id,
      "spec": str(spec.path),
      "prereg": spec.prereg,
      "bundle": (None if not spec.bundle else {
          "prefix": spec.bundle.prefix,
          "include_stages": spec.bundle.include_stages,
          "cloud_logs": spec.bundle.cloud_logs}),
      "stages": [{"name": s.name, "target": s.target, "kind": s.kind,
                  "on_failure": s.on_failure, "needs": s.needs} for s in spec.stages],
      "runs": [{"stage": r.stage, "kind": r.kind, "target": r.target,
                "run_id": r.run_id, "cmd": r.cmd, "vars": r.vars,
                "logdir": r.logdir, "outputs": r.outputs, "inputs": r.inputs,
                "done_when": [{p.kind: p.arg} for p in r.done_when]}
               for r in all_runs],
  }, indent=1) + "\n")

  # -- lane command files ----------------------------------------------------
  submit_lines = [hdr, "# Ship the wave dir to an instance, then queue each lane.",
                  "#   usage: submit.sh <instance>", "set -euo pipefail",
                  'N="${1:?usage: submit.sh <instance>}"',
                  'HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
                  ROOT_PREAMBLE.format(root=shlex.quote(str(_repo_root()))),
                  'source "$DV3OPS_ROOT/scripts/ops/lib/common.sh"',
                  'dv3_require_instance "$N"',
                  # The instance's RUNROOT is NOT this machine's: RCC is
                  # /scratch/midway3/<user>/dreamerv3_runs and a Vast box is
                  # /workspace/dreamerv3_runs. Ask the instance for its own.
                  #
                  # Both alternatives were live bugs, found on 2026-08-15 while
                  # submitting the sigma-ladder ridge stage -- the first real
                  # use of submit.sh: expanding "$RUNROOT" here sent the wave
                  # dir to an RCC path that does not exist on the instance,
                  # while leaving "$REMOTE" for the instance to expand hit an
                  # unset variable (it is defined only in THIS script), so the
                  # queue lines died on `set -u` after the rsync had already
                  # claimed success.
                  'REMOTE_ROOT="$(dv3_ssh_dv3 "$N" \'printf %s "$RUNROOT"\')"',
                  '[ -n "$REMOTE_ROOT" ] || { echo "ERROR: cannot read RUNROOT'
                  ' on instance $N" >&2; exit 1; }',
                  f'REMOTE="$REMOTE_ROOT/_waves/{spec.wave_id}"', "",
                  "# rsync rather than heredoc: no quoting survives ssh reliably,",
                  "# and it leaves the exact submitted commands on the instance.",
                  'dv3_ssh_dv3 "$N" "mkdir -p \\"$REMOTE\\""',
                  '# --checksum: these are small text files that can be',
                  '# regenerated at the same size, and size+mtime would skip them.',
                  'rsync -az --checksum --info=progress2 \\',
                  '  -e "ssh -p $(dv3_port "$N") ${DV3_SSH_OPTS[*]}" \\',
                  f'  "$HERE/" "root@$(dv3_ip "$N"):$REMOTE/"', ""]

  for st in spec.stages:
    if st.target != "vast":
      continue
    per_gpu = spec.kinds[st.kind].per_gpu if st.kind in spec.kinds else 1
    runs = wavespec.balanced_order(st.expanded())
    units = wavespec.pair_runs(runs, per_gpu)
    by_lane = wavespec.assign_lanes(units, lanes)
    for ln, lane_units in by_lane.items():
      if not lane_units:
        continue
      fname = f"lane_{st.name}_{ln}.cmds"
      body = [f"# {spec.wave_id} / stage {st.name} / lane {ln} / "
              f"{len(lane_units)} queued task(s), {sum(len(u) for u in lane_units)} run(s)"]
      for i, u in enumerate(lane_units):
        body.append(cmd_line(u, f"{spec.wave_id}_{st.name}_l{ln}_pair{i:02d}"))
      _w(out / fname, "\n".join(body) + "\n")
      summary["lane_files"].append(fname)
      abort = "1" if st.on_failure == "abort" else "0"
      submit_lines.append(
          f'echo "-- stage {st.name} lane {ln}: {len(lane_units)} task(s) --"')
      submit_lines.append(
          # Double quotes: $REMOTE must expand HERE, to the path we just
          # resolved on the instance, not remotely where it does not exist.
          f'dv3_ssh_dv3 "$N" "DV3_ABORT_ON_FAIL={abort} '
          f'dv3_queue_or_add \\"$REMOTE/{fname}\\" {ln}"')
  submit_lines += ["", 'echo "submitted. verify with: dv3ops status $N"']
  _w(out / "submit.sh", "\n".join(submit_lines) + "\n", executable=True)

  # -- RCC Slurm submission --------------------------------------------------
  slurm_runs = [r for r in all_runs if r.target == "rcc-slurm"]
  if slurm_runs:
    _w(out / "submit_rcc.sh", _gen_slurm(spec, slurm_runs, hdr), executable=True)
    summary["slurm_runs"] = len(slurm_runs)

  # -- preflight (remote half) ----------------------------------------------
  donors = sorted({i for r in all_runs for i in r.inputs})
  pf = [hdr, "# Run ON an instance. Every check here corresponds to a failure",
        "# that has actually cost work before.", "set -uo pipefail",
        "source /root/.dreamer_vast_env", "fail=0",
        'ok () { printf "  PASS %s\\n" "$1"; }',
        'bad () { printf "  FAIL %s\\n" "$1"; fail=1; }', "",
        'echo "== fork present (an empty $REPO fails as scattered ENOENT, never one message) =="',
        'for f in scripts/env.sh scripts/ops/instance_helpers.sh probing/__init__.py; do',
        '  [ -e "$REPO/$f" ] && ok "$f" || bad "MISSING $REPO/$f -- run push-repo"',
        "done", "",
        'echo "== interpreter =="',
        '"${CONDA_ENV:-/venv/main}/bin/python" -c "import sys" 2>/dev/null \\',
        '  && ok "python in $CONDA_ENV" || bad "python broken in ${CONDA_ENV:-/venv/main}"', "",
        # Instance 2, 2026-08-13: /usr/bin/rsync was a 0-byte non-executable
        # stub (disk filled mid-write). ssh still worked, so it presented as
        # "rsync: connection unexpectedly closed" from the RCC side -- a
        # sender-side error message for a receiver-side broken binary.
        'echo "== transfer tooling =="',
        'for b in rsync tar; do',
        '  p="$(command -v "$b" 2>/dev/null)"',
        '  if [ -z "$p" ]; then bad "MISSING $b"',
        '  elif [ ! -x "$p" ]; then bad "$b not executable ($p)"',
        '  elif [ ! -s "$p" ]; then bad "$b is a 0-byte stub ($p) -- reinstall it"',
        '  else ok "$b $(du -h "$p" | cut -f1)"; fi',
        "done", "",
        'echo "== disk =="',
        'pct="$(df -P "$RUNROOT" | awk \'NR==2{gsub(/%/,"",$5); print $5}\')"',
        '[ "${pct:-100}" -lt 90 ] && ok "disk ${pct}% used" || bad "disk ${pct}% used"', ""]
  if donors:
    pf += ['echo "== donors =="']
    for d in donors:
      pf.append(f'[ -e "$RUNROOT/{d}" ] && ok {shlex.quote(d)} || bad "MISSING donor {d}"')
    pf.append("")
  pf += ['echo "== helpers =="',
         'type dv3_queue_or_add >/dev/null 2>&1 && ok "helpers loaded ($(dv3_version))" \\',
         '  || bad "helpers not loaded -- run push-repo"', "",
         '[ "$fail" -eq 0 ] && echo "PREFLIGHT PASS" || echo "PREFLIGHT FAIL"',
         'exit "$fail"']
  _w(out / "preflight_remote.sh", "\n".join(pf) + "\n", executable=True)

  # -- donor push ------------------------------------------------------------
  if donors:
    inc = " \\\n  ".join(include_args(donors))
    _w(out / "push_donors.sh", f"""{hdr}# Push this wave's declared inputs to an instance.
#   usage: push_donors.sh <instance>
set -euo pipefail
N="${{1:?usage: push_donors.sh <instance>}}"
HERE="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
{ROOT_PREAMBLE.format(root=shlex.quote(str(_repo_root())))}source "$DV3OPS_ROOT/scripts/ops/lib/common.sh"
dv3_require_instance "$N"

# Fail before transferring rather than half way through: a missing donor is a
# spec error, and discovering it after 40 minutes of rsync is expensive.
missing=0
for d in {' '.join(shlex.quote(d) for d in donors)}; do
  [ -e "$RUNROOT/$d" ] || {{ echo "MISSING donor: $RUNROOT/$d" >&2; missing=1; }}
done
[ "$missing" -eq 0 ] || {{ echo "ERROR: donors missing on RCC; nothing pushed" >&2; exit 1; }}

dv3_ssh_dv3 "$N" 'mkdir -p "$RUNROOT"'
rsync "${{DV3_RSYNC_OPTS[@]}}" \\
  -e "ssh -p $(dv3_port "$N") ${{DV3_SSH_OPTS[*]}}" \\
  {inc} \\
  --exclude='*' \\
  "$RUNROOT/" "root@$(dv3_ip "$N"):/workspace/dreamerv3_runs/"
""", executable=True)

  # -- result pull -----------------------------------------------------------
  vast_runs = sorted({o for r in all_runs if r.target == "vast" for o in r.outputs})
  if vast_runs:
    inc = " \\\n  ".join(include_args(vast_runs))
    logs = " \\\n  ".join(
        f"--include={shlex.quote('/_cloud_logs/' + r + '.out')}" for r in vast_runs)
    _w(out / "pull_results.sh", f"""{hdr}# Pull this wave's results from an instance to RCC.
#   usage: pull_results.sh <instance> [instance...]
set -euo pipefail
HERE="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
{ROOT_PREAMBLE.format(root=shlex.quote(str(_repo_root())))}source "$DV3OPS_ROOT/scripts/ops/lib/common.sh"
[ $# -gt 0 ] || {{ echo "usage: pull_results.sh <instance>..." >&2; exit 2; }}

# rsync exit 24 is "some files vanished before they could be transferred". When
# the source instance is still COMPUTING -- which is the normal case, and the
# case worth pulling for -- checkpoints rotate mid-transfer and 24 is routine.
# It is a warning, not a failure. Under `set -e` it aborted the whole script
# after the first live instance, so every LATER instance was silently skipped
# and the run still looked like it had merely "finished" (2026-08-15: a pull of
# 1 2 3 7 stopped after 2, and only the log's missing "pulled" line showed it).
# 23 (partial transfer / real error) is NOT tolerated.
rs () {{
  rsync "$@"; local rc=$?
  [ "$rc" -eq 0 ] || [ "$rc" -eq 24 ] || return "$rc"
  [ "$rc" -eq 24 ] && echo "  (rsync 24: files rotated mid-copy on a live instance -- expected)"
  return 0
}}

failed=""
for N in "$@"; do
  dv3_require_instance "$N"
  echo "-- pull from instance $N --"

  # Pass 1: payload. Large, resumable, size/mtime based.
  rs "${{DV3_RSYNC_OPTS[@]}}" \\
    -e "ssh -p $(dv3_port "$N") ${{DV3_SSH_OPTS[*]}}" \\
    {inc} \\
    --include='/_cloud_logs/' \\
    {logs} \\
    --include='/_cloud_logs/worker_shard*.out' \\
    --include='/_cloud_logs/events.jsonl' \\
    --exclude='*' \\
    "root@$(dv3_ip "$N"):/workspace/dreamerv3_runs/" "$RUNROOT/"

  # Pass 2: mutable witnesses only, checksum-forced. An earlier mid-run pull
  # can leave a stale progress/marker file that size+mtime will not correct,
  # and a stale witness is read as truth by the checker. Deliberately NOT
  # --append-verify, and deliberately scoped to tiny files.
  rs -az -c --ignore-times --info=progress2 \\
    -e "ssh -p $(dv3_port "$N") ${{DV3_SSH_OPTS[*]}}" \\
    --include='*/' \\
    --include='TRAINING_DONE' --include='ADAPT_DONE' --include='DISTILL_DONE' \\
    --include='OFFLINE_FIT_PROGRESS' --include='config.yaml' \\
    --include='scores.jsonl' --include='fidelity.json' --include='done' \\
    --exclude='*' \\
    {inc} \\
    "root@$(dv3_ip "$N"):/workspace/dreamerv3_runs/" "$RUNROOT/" || failed="$failed $N"
done
if [ -n "$failed" ]; then
  echo "PULL INCOMPLETE for instance(s):$failed" >&2
  echo "  the others were pulled; re-run for just these once reachable" >&2
  exit 1
fi
echo "pulled. verify with: dv3ops check --wave {spec.wave_id}"
""", executable=True)

  # -- bundle ----------------------------------------------------------------
  if spec.bundle:
    br = sorted({o for r in all_runs if r.stage in spec.bundle.include_stages
                 for o in r.outputs})
    globs = spec.bundle.cloud_logs or []
    _w(out / "bundle.sh", f"""{hdr}# Bundle this wave for transfer to the analysis machine.
set -euo pipefail
HERE="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
{ROOT_PREAMBLE.format(root=shlex.quote(str(_repo_root())))}source "$DV3OPS_ROOT/scripts/ops/lib/common.sh"

bundle="$RUNROOT/bundles/{spec.bundle.prefix}_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$bundle/runroot" "$bundle/_cloud_logs"

# COMPLETION.txt is written by the same checker that gates the read, so the
# bundle cannot claim a completeness its own predicates would reject.
python3 "$DV3OPS_ROOT/scripts/ops/wavecheck.py" \\
  "$DV3OPS_ROOT/ops/waves/{spec.wave_id}" --runroot "$RUNROOT" \\
  > "$bundle/COMPLETION.txt" || true
cat "$bundle/COMPLETION.txt"

# Outputs may be directories (fits, adapts) or loose files in a shared folder
# (probe/E4), so preserve the relative path rather than flattening into runroot/.
for run in {' '.join(shlex.quote(r) for r in br)}; do
  if [ -e "$RUNROOT/$run" ]; then
    mkdir -p "$bundle/runroot/$(dirname "$run")"
    cp -al "$RUNROOT/$run" "$bundle/runroot/$run" 2>/dev/null \
      || cp -a "$RUNROOT/$run" "$bundle/runroot/$run"
  else
    echo "WARN: missing output $run" >&2
  fi
done

shopt -s nullglob
for pat in {' '.join(shlex.quote(g) for g in globs) or "''"}; do
  [ -n "$pat" ] || continue
  for f in "$RUNROOT"/_cloud_logs/$pat; do cp -a "$f" "$bundle/_cloud_logs/"; done
done

cp -a "$HERE/runs.json" "$HERE/RUN_IDS.txt" "$bundle/" 2>/dev/null || true
"$DV3OPS_ROOT/scripts/bundle_manifest.sh" generate "$bundle"
echo "$bundle"
""", executable=True)

  return summary


def main() -> int:
  ap = argparse.ArgumentParser(description=__doc__,
                               formatter_class=argparse.RawDescriptionHelpFormatter)
  ap.add_argument("wave", help="ops/waves/<id> directory or a spec.yaml path")
  ap.add_argument("--lanes", default="0,1,2,3",
                  help="lane ids for vast stages (default 0,1,2,3)")
  ap.add_argument("--out", default=None, help="output dir (default <wave>/generated)")
  ap.add_argument("--quiet", action="store_true")
  ap.add_argument("--only-runs", default=None, metavar="FILE",
                  help="regenerate lane files for just these run_ids (one per "
                       "line, e.g. `wavecheck.py --pending`). Used by requeue: "
                       "the retry set is derived from the checker, never retyped.")
  args = ap.parse_args()

  try:
    spec = wavespec.load(args.wave)
  except SpecError as e:
    print(f"SPEC ERROR: {e}", file=sys.stderr)
    return 2

  lanes = [x.strip() for x in args.lanes.split(",") if x.strip()]
  default_out = (Path(args.wave) if Path(args.wave).is_dir()
                 else spec.path.parent) / "generated"

  if args.only_runs:
    keep = {ln.strip() for ln in Path(args.only_runs).read_text().split() if ln.strip()}
    known = {r.run_id for r in spec.runs()}
    unknown = keep - known
    if unknown:
      print(f"ERROR: {len(unknown)} run_id(s) not in this wave: "
            f"{sorted(unknown)[:5]}", file=sys.stderr)
      return 2
    # Freeze the surviving runs as explicit entries. run_id and cmd are carried
    # verbatim from the original expansion, so a requeued task is byte-identical
    # to what first ran -- a retry must not be a re-derivation.
    for st in spec.stages:
      kept = [{**r.vars, "run_id": r.run_id, "cmd": r.cmd}
              for r in st.expanded() if r.run_id in keep]
      st.explicit_runs = kept
      st.expand = {}
    if not any(st.explicit_runs for st in spec.stages):
      print("nothing to requeue: every run in the filter is already complete")
      return 0

  out = Path(args.out) if args.out else default_out

  try:
    summary = gen(spec, out, lanes)
  except SpecError as e:
    print(f"SPEC ERROR: {e}", file=sys.stderr)
    return 2

  if not args.quiet:
    print((out / "RUN_IDS.txt").read_text())
    print(f"generated -> {out}")
    for st, info in summary["stages"].items():
      print(f"  stage {st:<12} {info['count']:>4} run(s)  target={info['target']:<10}"
            f" per_gpu={info['per_gpu']}  on_failure={info['on_failure']}")
    print(f"  lane files: {len(summary['lane_files'])}")
    print()
    print("APPROVAL GATE: nothing is submitted by this command. Read RUN_IDS.txt,")
    print("check it against the prereg, then run generated/submit.sh <instance>.")
  return 0


if __name__ == "__main__":
  sys.exit(main())
