# ---------------------------------------------------------------------------
# dv3ops shared library -- RCC side  (P0, 2026-08-14)
#
# The canonical command shapes, once, in code. Every shape in here was lifted
# from a pattern in temp_files/ops/instance_sample_commands.md; the prose there
# stays as the rationale, this file is the implementation.
#
# The ssh helpers exist specifically to contain the §0.9 hazard: ssh joins its
# arguments into ONE string and hands it to a remote login shell that re-parses
# it, so every argument containing a space silently splits and shifts every
# later positional. That cost 12 of 16 jobs on 2026-07-24 with no error
# anywhere. dv3_ssh_args pre-quotes with printf %q so it cannot recur.
# ---------------------------------------------------------------------------

DV3OPS_ROOT="${DV3OPS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
DV3OPS_STATE="${DV3OPS_STATE:-$DV3OPS_ROOT/ops/state}"

: "${REPO:=$DV3OPS_ROOT}"
: "${RUNROOT:=/scratch/midway3/$USER/dreamerv3_runs}"

DV3_SSH_OPTS=(-o ServerAliveInterval=30 -o ServerAliveCountMax=120
              -o StrictHostKeyChecking=accept-new)

DV3_RSYNC_OPTS=(-az --partial --append-verify --info=progress2 --stats)

DV3_REPO_EXCLUDES=(--exclude='.git/' --exclude='local_results/' --exclude='artifacts/'
                   --exclude='research_notes/' --exclude='__pycache__/'
                   --exclude='*.pyc' --exclude='ops/state/')

die () { echo "ERROR: $*" >&2; exit 1; }
note () { echo "[dv3ops] $*"; }

# --- instance resolution ----------------------------------------------------
# Prefers ops/state/instances.env (generated by `dv3ops refresh`, P2). Falls
# back to IP<N>/PORT<N> already exported in the shell, which is the current
# hand-maintained practice -- so P0 works before P2 exists.

dv3_load_instances () {
  [ -r "$DV3OPS_STATE/instances.env" ] && source "$DV3OPS_STATE/instances.env"
  return 0
}

dv3_ip ()   { local n="${1:?instance}"; local v="IP${n}";   printf '%s' "${!v:-}"; }
dv3_port () { local n="${1:?instance}"; local v="PORT${n}"; printf '%s' "${!v:-}"; }

dv3_require_instance () {
  local n="${1:?instance}"
  dv3_load_instances
  [ -n "$(dv3_ip "$n")" ] && [ -n "$(dv3_port "$n")" ] ||
    die "instance $n unknown: set IP${n}/PORT${n}, or run 'dv3ops refresh' (P2)"
}

# --- ssh --------------------------------------------------------------------

# Run a command string on an instance. The string is passed as ONE argument to
# a login shell -- never build it by concatenating unquoted variables.
dv3_ssh () {
  local n="${1:?instance}"; shift
  dv3_require_instance "$n"
  ssh -p "$(dv3_port "$n")" "${DV3_SSH_OPTS[@]}" "root@$(dv3_ip "$n")" "$@"
}

# Feed a heredoc/script to an instance with positional args that survive the
# remote re-parse. Usage:
#   dv3_ssh_script 4 "$script_text" arg1 "arg with spaces" arg3
dv3_ssh_script () {
  local n="${1:?instance}" script="${2:?script}"; shift 2
  local quoted=""
  [ $# -gt 0 ] && quoted="$(printf '%q ' "$@")"
  dv3_require_instance "$n"
  printf '%s\n' "$script" |
    ssh -p "$(dv3_port "$n")" "${DV3_SSH_OPTS[@]}" "root@$(dv3_ip "$n")" \
      "bash -s -- $quoted"
}

# Same, but sources env + helpers first: the common case.
dv3_ssh_dv3 () {
  local n="${1:?instance}" script="${2:?script}"; shift 2
  dv3_ssh_script "$n" "$(printf 'set -uo pipefail\nsource /root/.dreamer_vast_env\nsource /root/dreamer_instance_helpers.sh\ncd "$REPO"\n%s\n' "$script")" "$@"
}

# --- repo sync --------------------------------------------------------------
# Canonical whole-repo shape. Do NOT replace with multi-source trailing-slash
# syncs: those copy package contents into the repo root and create top-level
# ./jax, ./agent.py etc. that shadow installed packages.

dv3_stamp_version () {
  local sha dirty=""
  sha="$(git -C "$DV3OPS_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  git -C "$DV3OPS_ROOT" diff --quiet 2>/dev/null || dirty="-dirty"
  printf '%s%s pushed=%s by=%s\n' "$sha" "$dirty" "$(date -Is)" "${USER:-unknown}" \
    > "$DV3OPS_ROOT/scripts/ops/VERSION"
  printf '%s%s' "$sha" "$dirty"
}

dv3_push_repo () {
  local n="${1:?instance}" ver
  dv3_require_instance "$n"
  ver="$(dv3_stamp_version)"
  note "push-repo -> instance $n  (repo $ver)"
  rsync "${DV3_RSYNC_OPTS[@]}" --delete "${DV3_REPO_EXCLUDES[@]}" \
    -e "ssh -p $(dv3_port "$n") ${DV3_SSH_OPTS[*]}" \
    "$DV3OPS_ROOT/" "root@$(dv3_ip "$n"):/workspace/dreamerv3/"
  # Backfill notification config into /root/.dreamer_vast_env.
  # An instance that predates the new onstart template -- or one that REBOOTED
  # and re-ran the old template -- has no DV3_NTFY_* vars, so the watchdog comes
  # up correctly and then reports to nobody. That failure is invisible by
  # construction: silence is exactly what a healthy night looks like.
  dv3_ssh_script "$n" '
set -uo pipefail
label="$1"; topic="$2"
env_file=/root/.dreamer_vast_env
for kv in "DV3_INSTANCE_LABEL=$label" "DV3_NTFY_TOPIC=$topic"; do
  key="${kv%%=*}"
  if grep -q "^export $key=..*" "$env_file" 2>/dev/null; then
    echo "  keep $key (already set)"
  else
    sed -i "/^export $key=/d" "$env_file" 2>/dev/null || true
    echo "export $kv" >> "$env_file"
    echo "  set  $kv"
  fi
done
grep -q "^export DV3_HC_URL=" "$env_file" 2>/dev/null || echo "export DV3_HC_URL=" >> "$env_file"
' "inst${n}" "${DV3_NTFY_TOPIC:-dreamerv3_ops_notification}"

  dv3_ssh_dv3 "$n" '
    chmod +x "$REPO"/scripts/ops/*.sh "$REPO"/scripts/ops/runners/*.sh 2>/dev/null || true
    echo "helpers: $(dv3_version)"
    bash "$REPO/scripts/ops/watchdog.sh" start || echo "WARN: watchdog did not start"
    bash "$REPO/scripts/ops/watchdog.sh" status
  '
}
