# ---------------------------------------------------------------------------
# dv3ops shared library -- RCC side  (P0, 2026-08-14)
#
# The canonical command shapes, once, in code. Every shape in here was lifted
# from a pattern in temp_files/ops/instance_sample_commands.md; the prose there
# stays as the rationale, this file is the implementation.
#
# The ssh helpers exist specifically to contain the §0.9 hazard: ssh joins its
# arguments into ONE string and hands it to a remote login shell that re-parses
# it, so every argument containing a space silently splits and shifts every
# later positional. That cost 12 of 16 jobs on 2026-07-24 with no error
# anywhere. dv3_ssh_args pre-quotes with printf %q so it cannot recur.
# ---------------------------------------------------------------------------

DV3OPS_ROOT="${DV3OPS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
DV3OPS_STATE="${DV3OPS_STATE:-$DV3OPS_ROOT/ops/state}"

: "${REPO:=$DV3OPS_ROOT}"
: "${RUNROOT:=/scratch/midway3/$USER/dreamerv3_runs}"

DV3_SSH_OPTS=(-o ServerAliveInterval=30 -o ServerAliveCountMax=120
              -o StrictHostKeyChecking=accept-new)

DV3_RSYNC_OPTS=(-az --partial --append-verify --info=progress2 --stats)

DV3_REPO_EXCLUDES=(--exclude='.git/' --exclude='local_results/' --exclude='artifacts/'
                   --exclude='research_notes/' --exclude='__pycache__/'
                   --exclude='*.pyc' --exclude='ops/state/')

die () { echo "ERROR: $*" >&2; exit 1; }
note () { echo "[dv3ops] $*"; }

# --- instance resolution ----------------------------------------------------
# Prefers ops/state/instances.env (generated by `dv3ops refresh`, P2). Falls
# back to IP<N>/PORT<N> already exported in the shell, which is the current
# hand-maintained practice -- so P0 works before P2 exists.

dv3_load_instances () {
  if [ -r "$DV3OPS_STATE/instances.env" ]; then
    source "$DV3OPS_STATE/instances.env"
    return 0
  fi
  # Say where we looked. ops/state/ is gitignored, so it does NOT arrive with a
  # git pull -- on a second machine it has to be created and copied explicitly,
  # and the symptom otherwise is a bare "no instances reported".
  if [ -z "${DV3_QUIET_STATE:-}" ] && [ -z "${IP1:-}" ]; then
    echo "note: no instance inventory at $DV3OPS_STATE/instances.env" >&2
    if [ -e "$DV3OPS_STATE" ] && [ ! -d "$DV3OPS_STATE" ]; then
      echo "      ($DV3OPS_STATE exists but is NOT a directory -- an scp into a" >&2
      echo "       missing path can create a file with that name; remove it)" >&2
    fi
    echo "      fix: mkdir -p $DV3OPS_STATE, then from WSL:" >&2
    echo "        dv3ops refresh --push-to <user@rcc>:$DV3OPS_STATE/" >&2
    echo "      or export IP<N>/PORT<N> in this shell." >&2
  fi
  return 0
}

dv3_ip ()   { local n="${1:?instance}"; local v="IP${n}";   printf '%s' "${!v:-}"; }
dv3_port () { local n="${1:?instance}"; local v="PORT${n}"; printf '%s' "${!v:-}"; }

dv3_require_instance () {
  local n="${1:?instance}"
  dv3_load_instances
  [ -n "$(dv3_ip "$n")" ] && [ -n "$(dv3_port "$n")" ] ||
    die "instance $n unknown: set IP${n}/PORT${n}, or run 'dv3ops refresh' (P2)"
}

# --- ssh --------------------------------------------------------------------

# Run a command string on an instance. The string is passed as ONE argument to
# a login shell -- never build it by concatenating unquoted variables.
#
# `-n` is load-bearing, not tidiness. ssh reads stdin by default, so an ssh
# call inside a script that is ITSELF being fed on stdin -- the
# `ssh host 'bash -s' <<'EOF' ... ssh host 'mkdir -p ...' ... EOF` shape --
# swallows the remainder of the enclosing script. Every command after it
# silently never runs, with no error: exactly the "rsync after an ssh mkdir
# doesn't execute" symptom. `-n` redirects stdin from /dev/null so an inner
# ssh cannot eat its parent.
dv3_ssh () {
  local n="${1:?instance}"; shift
  dv3_require_instance "$n"
  ssh -n -p "$(dv3_port "$n")" "${DV3_SSH_OPTS[@]}" "root@$(dv3_ip "$n")" "$@"
}

# Feed a heredoc/script to an instance with positional args that survive the
# remote re-parse. Usage:
#   dv3_ssh_script 4 "$script_text" arg1 "arg with spaces" arg3
dv3_ssh_script () {
  local n="${1:?instance}" script="${2:?script}"; shift 2
  local quoted=""
  [ $# -gt 0 ] && quoted="$(printf '%q ' "$@")"
  dv3_require_instance "$n"
  printf '%s\n' "$script" |
    ssh -p "$(dv3_port "$n")" "${DV3_SSH_OPTS[@]}" "root@$(dv3_ip "$n")" \
      "bash -s -- $quoted"
}

# Same, but sources env + helpers first: the common case.
dv3_ssh_dv3 () {
  local n="${1:?instance}" script="${2:?script}"; shift 2
  dv3_ssh_script "$n" "$(printf 'set -uo pipefail\nsource /root/.dreamer_vast_env\nsource /root/dreamer_instance_helpers.sh\ncd "$REPO"\n%s\n' "$script")" "$@"
}

# --- repo sync --------------------------------------------------------------
# Canonical whole-repo shape. Do NOT replace with multi-source trailing-slash
# syncs: those copy package contents into the repo root and create top-level
# ./jax, ./agent.py etc. that shadow installed packages.

dv3_stamp_version () {
  local sha dirty=""
  sha="$(git -C "$DV3OPS_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  git -C "$DV3OPS_ROOT" diff --quiet 2>/dev/null || dirty="-dirty"
  printf '%s%s pushed=%s by=%s\n' "$sha" "$dirty" "$(date -Is)" "${USER:-unknown}" \
    > "$DV3OPS_ROOT/scripts/ops/VERSION"
  printf '%s%s' "$sha" "$dirty"
}

dv3_push_repo () {
  local n="${1:?instance}" ver
  dv3_require_instance "$n"
  ver="$(dv3_stamp_version)"
  note "push-repo -> instance $n  (repo $ver)"
  rsync "${DV3_RSYNC_OPTS[@]}" --delete "${DV3_REPO_EXCLUDES[@]}" \
    -e "ssh -p $(dv3_port "$n") ${DV3_SSH_OPTS[*]}" \
    "$DV3OPS_ROOT/" "root@$(dv3_ip "$n"):/workspace/dreamerv3/"
  # Install/refresh the helper shim at /root/dreamer_instance_helpers.sh.
  #
  # Without this, push-repo delivers new helpers to $REPO but leaves whatever
  # /root/dreamer_instance_helpers.sh the instance booted with -- and on an
  # instance created (or REBOOTED) under the v1 onstart template that file is
  # the whole v1 library, inline. The result is split-brain: the watchdog
  # sources the repo copy and works, while every interactive shell and every
  # dv3_ssh_dv3 call gets v1 and reports `dv3_version: command not found`.
  # Writing the shim here makes push-repo self-sufficient regardless of which
  # template vintage the instance came up on.
  dv3_ssh_script "$n" '
set -uo pipefail
real="${REPO:-/workspace/dreamerv3}/scripts/ops/instance_helpers.sh"
[ -r "$real" ] || { echo "  ERROR: helpers not synced to $real" >&2; exit 1; }
if [ -f /root/dreamer_instance_helpers.sh ] &&
   ! grep -q "scripts/ops/instance_helpers.sh" /root/dreamer_instance_helpers.sh 2>/dev/null; then
  cp -a /root/dreamer_instance_helpers.sh /root/dreamer_instance_helpers.v1.bak
  echo "  replacing inline v1 helpers (backed up to /root/dreamer_instance_helpers.v1.bak)"
fi
cat > /root/dreamer_instance_helpers.sh <<SHIM
DV3_HELPERS_REAL="\${REPO:-/workspace/dreamerv3}/scripts/ops/instance_helpers.sh"
if [ -r "\$DV3_HELPERS_REAL" ]; then
  source "\$DV3_HELPERS_REAL"
else
  echo "dv3: helpers not installed yet -- run '"'"'dv3ops push-repo <N>'"'"' from RCC" >&2
fi
SHIM
chmod 644 /root/dreamer_instance_helpers.sh
echo "  shim installed -> $real"
'

  # Backfill notification config into /root/.dreamer_vast_env.
  # An instance that predates the new onstart template -- or one that REBOOTED
  # and re-ran the old template -- has no DV3_NTFY_* vars, so the watchdog comes
  # up correctly and then reports to nobody. That failure is invisible by
  # construction: silence is exactly what a healthy night looks like.
  dv3_ssh_script "$n" '
set -uo pipefail
label="$1"; topic="$2"
env_file=/root/.dreamer_vast_env
for kv in "DV3_INSTANCE_LABEL=$label" "DV3_NTFY_TOPIC=$topic"; do
  key="${kv%%=*}"
  if grep -q "^export $key=..*" "$env_file" 2>/dev/null; then
    echo "  keep $key (already set)"
  else
    sed -i "/^export $key=/d" "$env_file" 2>/dev/null || true
    echo "export $kv" >> "$env_file"
    echo "  set  $kv"
  fi
done
grep -q "^export DV3_HC_URL=" "$env_file" 2>/dev/null || echo "export DV3_HC_URL=" >> "$env_file"
' "inst${n}" "${DV3_NTFY_TOPIC:-dreamerv3_ops_notification}"

  dv3_ssh_dv3 "$n" '
    chmod +x "$REPO"/scripts/ops/*.sh "$REPO"/scripts/ops/runners/*.sh 2>/dev/null || true
    echo "helpers: $(dv3_version)"
    # RESTART, not start: `start` sees the pidfile and leaves the old process
    # running the old code, so a push that fixes the watchdog would not take
    # effect until the instance rebooted. Safe to bounce -- it only observes,
    # holds no queue state, and its dedupe markers live on disk.
    bash "$REPO/scripts/ops/watchdog.sh" stop >/dev/null 2>&1 || true
    bash "$REPO/scripts/ops/watchdog.sh" start || echo "WARN: watchdog did not start"
    bash "$REPO/scripts/ops/watchdog.sh" status
  '
}
