# GENERATED by scripts/ops/wavegen.py from ops/waves/b1prime/spec.yaml -- do not edit by hand.
# Bundle this wave for transfer to the analysis machine.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DV3OPS_ROOT="${DV3OPS_ROOT:-/home/rickybao/projects/dreamerv3}"
[ -f "$DV3OPS_ROOT/scripts/ops/lib/common.sh" ] || {
  echo "ERROR: repo not found at DV3OPS_ROOT=$DV3OPS_ROOT" >&2
  echo "       (set DV3OPS_ROOT if the repo lives elsewhere on this machine)" >&2
  exit 2; }
source "$DV3OPS_ROOT/scripts/ops/lib/common.sh"

bundle="$RUNROOT/bundles/b1prime_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$bundle/runroot" "$bundle/_cloud_logs"

# COMPLETION.txt is written by the same checker that gates the read, so the
# bundle cannot claim a completeness its own predicates would reject.
python3 "$DV3OPS_ROOT/scripts/ops/wavecheck.py" \
  "$DV3OPS_ROOT/ops/waves/b1prime" --runroot "$RUNROOT" \
  > "$bundle/COMPLETION.txt" || true
cat "$bundle/COMPLETION.txt"

# Outputs may be directories (fits, adapts) or loose files in a shared folder
# (probe/E4), so preserve the relative path rather than flattening into runroot/.
for run in adapt_ax1fsk6q1s0_finger_seed3_ckpt500000 adapt_ax1fsk6q1s0_finger_seed4_ckpt500000 adapt_ax1fsk6q1s1_finger_seed3_ckpt500000 adapt_ax1fsk6q1s1_finger_seed4_ckpt500000 ax1wm_finger_fsk6q1s0_seed3 ax1wm_finger_fsk6q1s0_seed4 ax1wm_finger_fsk6q1s1_seed3 ax1wm_finger_fsk6q1s1_seed4; do
  if [ -e "$RUNROOT/$run" ]; then
    mkdir -p "$bundle/runroot/$(dirname "$run")"
    cp -al "$RUNROOT/$run" "$bundle/runroot/$run" 2>/dev/null       || cp -a "$RUNROOT/$run" "$bundle/runroot/$run"
  else
    echo "WARN: missing output $run" >&2
  fi
done

shopt -s nullglob
for pat in 'adapt_ax1sk6q1s*_finger_seed*.out' 'adapt_ax1fsk6q1s*_finger_seed*.out' 'worker_shard*.out'; do
  [ -n "$pat" ] || continue
  for f in "$RUNROOT"/_cloud_logs/$pat; do cp -a "$f" "$bundle/_cloud_logs/"; done
done

cp -a "$HERE/runs.json" "$HERE/RUN_IDS.txt" "$bundle/" 2>/dev/null || true
"$DV3OPS_ROOT/scripts/bundle_manifest.sh" generate "$bundle"
echo "$bundle"
